# Generated by Django 4.2.4 on 2023-09-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='openaiAnswersPreferences',
            field=models.CharField(blank=True, choices=[('formal', 'Formal'), ('friendly', 'Friendly'), ('emojis', 'With Emojis')], max_length=50, null=True),
        ),
    ]
